#!/usr/bin/env bash
# ── VCore Backup Installer ────────────────────────────────────────────────────
# Sets up nightly 2am backup via macOS launchd.
# Usage: ./install.sh
# Uninstall: ./install.sh --uninstall
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLIST_LABEL="com.vcore.secondbrain.backup"
PLIST_PATH="${HOME}/Library/LaunchAgents/${PLIST_LABEL}.plist"
CONFIG_FILE="${SCRIPT_DIR}/.backup-config"
BACKUP_SCRIPT="${SCRIPT_DIR}/backup.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  VCore SecondBrain Backup Installer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Uninstall ──────────────────────────────────────────────────────────────────
if [[ "${1:-}" == "--uninstall" ]]; then
  if launchctl list | grep -q "${PLIST_LABEL}" 2>/dev/null; then
    launchctl unload "${PLIST_PATH}" 2>/dev/null || true
    echo "→ Unloaded launchd job"
  fi
  if [[ -f "${PLIST_PATH}" ]]; then
    rm "${PLIST_PATH}"
    echo "→ Removed plist: ${PLIST_PATH}"
  fi
  echo "✅ Backup job uninstalled. Scripts remain at: ${SCRIPT_DIR}"
  echo ""
  exit 0
fi

# ── Collect config ─────────────────────────────────────────────────────────────
echo "Step 1: Source directory"
echo "  Default: /SecondBrain"
read -r -p "  SecondBrain path [/SecondBrain]: " SOURCE_INPUT
SOURCE_DIR="${SOURCE_INPUT:-/SecondBrain}"

echo ""
echo "Step 2: Backup destination"
echo "  This should be your external drive path."
echo "  Example: /Volumes/Samsung_T7/VCoreBackups"
echo "  Example: /Volumes/Backup/SecondBrainBackups"
read -r -p "  Backup root path: " BACKUP_ROOT
while [[ -z "${BACKUP_ROOT}" ]]; do
  echo "  ⚠️  Backup root is required."
  read -r -p "  Backup root path: " BACKUP_ROOT
done

echo ""
echo "Step 3: Retention period"
read -r -p "  Keep how many days of backups? [30]: " KEEP_INPUT
KEEP_DAYS="${KEEP_INPUT:-30}"

echo ""
echo "Step 4: Log directory"
read -r -p "  Log directory [${SOURCE_DIR}/Logs]: " LOG_INPUT
LOG_DIR="${LOG_INPUT:-${SOURCE_DIR}/Logs}"

# ── Write config file ──────────────────────────────────────────────────────────
cat > "${CONFIG_FILE}" <<EOF
# VCore Backup Configuration
# Generated by install.sh on $(date)
# Edit these values and re-run install.sh to update the launchd job.

VCORE_SOURCE="${SOURCE_DIR}"
VCORE_BACKUP_ROOT="${BACKUP_ROOT}"
VCORE_KEEP_DAYS="${KEEP_DAYS}"
VCORE_LOG_DIR="${LOG_DIR}"
EOF
echo ""
echo "→ Config written: ${CONFIG_FILE}"

# ── Create LaunchAgents dir ────────────────────────────────────────────────────
mkdir -p "${HOME}/Library/LaunchAgents"

# ── Write plist ────────────────────────────────────────────────────────────────
cat > "${PLIST_PATH}" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${PLIST_LABEL}</string>

  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>${BACKUP_SCRIPT}</string>
  </array>

  <key>StartCalendarInterval</key>
  <dict>
    <key>Hour</key>
    <integer>2</integer>
    <key>Minute</key>
    <integer>0</integer>
  </dict>

  <key>EnvironmentVariables</key>
  <dict>
    <key>VCORE_SOURCE</key>
    <string>${SOURCE_DIR}</string>
    <key>VCORE_BACKUP_ROOT</key>
    <string>${BACKUP_ROOT}</string>
    <key>VCORE_KEEP_DAYS</key>
    <string>${KEEP_DAYS}</string>
    <key>VCORE_LOG_DIR</key>
    <string>${LOG_DIR}</string>
  </dict>

  <key>StandardOutPath</key>
  <string>${LOG_DIR}/backup-stdout.log</string>

  <key>StandardErrorPath</key>
  <string>${LOG_DIR}/backup-stderr.log</string>

  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
EOF
echo "→ Plist written: ${PLIST_PATH}"

# ── Load the job ───────────────────────────────────────────────────────────────
# Unload first if already installed
launchctl unload "${PLIST_PATH}" 2>/dev/null || true
launchctl load "${PLIST_PATH}"
echo "→ Launchd job loaded"

# ── Verify ─────────────────────────────────────────────────────────────────────
echo ""
if launchctl list | grep -q "${PLIST_LABEL}"; then
  echo "✅ Backup job installed and active"
else
  echo "⚠️  Job may not have loaded — check: launchctl list | grep vcore"
fi

# ── Run test ───────────────────────────────────────────────────────────────────
echo ""
read -r -p "Run a dry-run backup now to verify? [Y/n]: " TEST_INPUT
if [[ "${TEST_INPUT:-Y}" =~ ^[Yy]$ ]]; then
  echo ""
  bash "${BACKUP_SCRIPT}" --dry-run
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Setup Complete"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Schedule:   Daily at 2:00 AM"
echo "  Source:     ${SOURCE_DIR}"
echo "  Destination:${BACKUP_ROOT}"
echo "  Retention:  ${KEEP_DAYS} days"
echo "  Logs:       ${LOG_DIR}/"
echo ""
echo "  Commands:"
echo "  • Manual backup:    bash ${BACKUP_SCRIPT}"
echo "  • Dry run:          bash ${BACKUP_SCRIPT} --dry-run"
echo "  • Restore:          bash ${SCRIPT_DIR}/restore.sh"
echo "  • List backups:     bash ${SCRIPT_DIR}/restore.sh"
echo "  • Uninstall:        bash ${SCRIPT_DIR}/install.sh --uninstall"
echo "  • Check job:        launchctl list | grep vcore"
echo ""
